name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build backend
        run: |
          cd backend
          gradle clean build -x test

      - name: Build frontend
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push backend
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/backend:latest ./backend
          docker push ghcr.io/${{ github.repository_owner }}/backend:latest

      - name: Build & push frontend
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/frontend:latest ./frontend
          docker push ghcr.io/${{ github.repository_owner }}/frontend:latest

      - name: Deploy to staging
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          script: |
            cd /srv/violeta
            docker compose pull
            docker compose up -d
